apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: platform
  name: platform-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
      - name: platform
        image: edrisym/platform:latest
---
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platform
  ports:
  - name: platform
    protocol: TCP
    port: 80
    targetPort: 80
